# Trusted build input: compile the SDK-only helper before embedding its exact
# bytes. Does not execute the helper, install or register any generation.
param([Parameter(Mandatory=$true)][string]$OutputDirectory, [switch]$EmbedAsset)
$ErrorActionPreference = 'Stop'
$repo = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$destination = [IO.Path]::GetFullPath($OutputDirectory)
New-Item -ItemType Directory -Path $destination -Force | Out-Null
$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
$vs = & $vswhere -latest -products '*' -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
if (!$vs) { throw 'Windows SDK/MSVC build installation unavailable' }
$msbuild = Join-Path $vs 'MSBuild\Current\Bin\MSBuild.exe'
foreach ($project in @('Callback', 'Contracts')) {
  $obj = Join-Path $destination "obj-$project"
  & $msbuild (Join-Path $PSScriptRoot "$project.vcxproj") /t:Build /p:Configuration=Release /p:Platform=x64 "/p:OutDir=$destination\" "/p:IntDir=$obj\" /verbosity:minimal "/bl:$destination\$project.binlog"
  if ($LASTEXITCODE -ne 0) { throw "$project native SDK build failed" }
}
$helper = Join-Path $destination 'helper.exe'
$digest = (Get-FileHash -LiteralPath $helper -Algorithm SHA256).Hash.ToLowerInvariant()
$source = (git -C $repo rev-parse HEAD).Trim()
if ($LASTEXITCODE -ne 0) { throw 'source identity unavailable' }
@{sourceSHA=$source; helperSHA256=$digest; readerVersion=1; architecture='amd64'; helperExecuted=$false; installedQualified=$false} |
  ConvertTo-Json | Set-Content -LiteralPath (Join-Path $destination 'build-evidence.json') -Encoding utf8
if ($EmbedAsset) {
  $asset = Join-Path $repo 'internal\windowscallback'
  Copy-Item -LiteralPath $helper -Destination (Join-Path $asset 'helper_generated.exe') -Force
  # Generated only from actual compiled bytes; unavailable build has no placeholder.
  $generated = @"
//go:build windows && amd64 && windows_callback_asset

// Code generated by native/windows-callback/build.ps1; DO NOT EDIT.
package windowscallback

import _ "embed"

//go:embed helper_generated.exe
var helperBytes []byte
const helperDigest = "$digest"
"@
  [IO.File]::WriteAllText((Join-Path $asset 'asset_generated.go'), $generated + "`n", [Text.UTF8Encoding]::new($false))
}
