package windowscallback

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
)

var ErrUnavailable = errors.New("windows callback installed qualification unavailable")

type Outcome string

const (
	Unavailable Outcome = "unavailable"
	Declined    Outcome = "declined"
	Accepted    Outcome = "accepted"
	Unknown     Outcome = "unknown"
)

// Result does not expose HRESULT or claim focus/render or an exact FullName lock.
type Result struct {
	Outcome         Outcome
	EffectEntered   bool
	TargetConfirmed bool
}
type Binding struct{ SnapshotPath, SHA256 string }
type NativePort interface {
	CheckReadiness(context.Context, Binding, uint64) error
}

// Port is intentionally inert until checkpoint B installs and qualifies the
// actual custody/readiness/submission contract. Even present release bytes do
// not enable this adapter. Construction and calls perform no native probes.
type Port struct{ asset helperAsset }
type helperAsset struct {
	bytes  []byte
	digest string
}

// NewPort captures release bytes without inspecting them or any installed state.
// The Windows session retains this value as the future explicit setup seam.
func NewPort() Port { return Port{asset: helperAsset{helperBytes, helperDigest}} }

// TrustedAsset validates the captured immutable bytes only when explicit setup
// asks for extraction. Construction and CheckReadiness never call this method.
func (p Port) TrustedAsset() ([]byte, string, error) { return trustedAsset(p.asset) }

func (Port) CheckReadiness(ctx context.Context, _ Binding, _ uint64) error {
	if e := ctx.Err(); e != nil {
		return e
	}
	return ErrUnavailable
}

// TrustedAsset is a defensive copy of bytes generated by the release build.
// No caller-supplied hash, PATH lookup or runtime download can supply provenance.
func TrustedAsset() ([]byte, string, error) { return NewPort().TrustedAsset() }
func trustedAsset(asset helperAsset) ([]byte, string, error) {
	if len(asset.bytes) == 0 || len(asset.digest) != 64 {
		return nil, "", ErrUnavailable
	}
	d := sha256.Sum256(asset.bytes)
	if hex.EncodeToString(d[:]) != asset.digest {
		return nil, "", ErrUnavailable
	}
	return append([]byte(nil), asset.bytes...), asset.digest, nil
}
